name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.2.2
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"

  hassfest:
    name: Hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
